[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[build.args]
DATABASE_URL = "${{Postgres.DATABASE_URL}}"
NEXTAUTH_SECRET = "${{NEXTAUTH_SECRET}}"
CALENDSO_ENCRYPTION_KEY = "${{CALENDSO_ENCRYPTION_KEY}}"
CALCOM_TELEMETRY_DISABLED = "1"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
